#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u
set -x

internal="LVDS1"
urt="/opt/UrbanTerror/ioUrbanTerror.x86_64"

set_dl_url() {
	cd "$HOME/.q3a/q3ut4"
	# Find the current IP address for the map download.
	ifconfig=$(ifconfig | grep -v 127.0.0.1 | grep -oP 'inet Adresse:([\d\.]+)')
	ip=${ifconfig#inet Adresse:}

	echo 'sets sv_dlURL "'$ip'"' >> q3config.cfg
}

set_resolution() {
	cd "$HOME/.q3a/q3ut4"
	mv q3config.cfg q3config.tmp
	grep -vP '^seta r_custom(?:width|height)' q3config.tmp > q3config.cfg
	echo "seta r_customwidth \"$1\"" >> q3config.cfg
	echo "seta r_customheight \"$2\"" >> q3config.cfg
}

if xrandr | grep -P 'HDMI\d? connected'
then
	set_resolution 1920 1200
	set_dl_url
	xrandr --output "$internal" --off
	"$urt"
	think-dock on
else
	set_resolution 1366 768
	set_dl_url
	"$urt"
fi
