#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.

set -e
set -u
set -x

internal="LVDS1"
urt="/opt/UrbanTerror/ioUrbanTerror.x86_64"

set_dl_url() {
	cd "$HOME/.q3a/q3ut4"
	# Find the current IP address for the map download.
	ifconfig=$(ifconfig | grep -v 127.0.0.1 | grep -oP 'inet Adresse:([\d\.]+)')
	ip=${ifconfig#inet Adresse:}

	echo 'sets sv_dlURL "'$ip'"' >> q3config.cfg
}

set_resolution() {
	cd "$HOME/.q3a/q3ut4"
	mv q3config.cfg q3config.tmp
	grep -vP '^seta r_custom(?:width|height)' q3config.tmp > q3config.cfg
	echo "seta r_customwidth \"$1\"" >> q3config.cfg
	echo "seta r_customheight \"$2\"" >> q3config.cfg
}

cleanup() {
	xgamma -gamma 1.0
}

trap cleanup EXIT

if xrandr | grep -P 'HDMI\d? connected'
then
	set_resolution 1920 1200
	set_dl_url
	xrandr --output "$internal" --off
	"$urt"
	think-dock on
else
	xgamma -gamma 1.4
	set_resolution 1366 768
	set_dl_url
	"$urt"
fi
