#!/bin/bash
# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

set -e
set -u
set -x

cd "$HOME/.q3a/q3ut4"

rm -f q3config.cfg

case "$1" in
	24)
		ln -s q3config-24.cfg q3config.cfg
		;;
	12)
		ln -s q3config-12.cfg q3config.cfg
		;;

/opt/UrbanTerror/ioUrbanTerror.x86_64
